@UnityServerProject_HostAddress = https://localhost:7185

GET {{UnityServerProject_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{UnityServerProject_HostAddress}}/userPlayData
Content-Type:application/json

{
  "startTime": 0,
  "endTime": 10.4,
  "deadCount": 0
}
###

GET {{UnityServerProject_HostAddress}}/userPlayData

###
