// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnityServerProject.Data;

#nullable disable

namespace UnityServerProject.Migrations
{
    [DbContext(typeof(PlaytestDb))]
    [Migration("20260216073705_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UnityServerProject.Model.DeathInfo", b =>
                {
                    b.Property<int>("DeathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeathId"));

                    b.Property<float>("DeathPositionX")
                        .HasColumnType("float");

                    b.Property<float>("DeathPositionY")
                        .HasColumnType("float");

                    b.Property<string>("EnemyName")
                        .HasColumnType("longtext");

                    b.Property<float>("EnemyPositionX")
                        .HasColumnType("float");

                    b.Property<float>("EnemyPositionY")
                        .HasColumnType("float");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("DeathId");

                    b.HasIndex("StageId");

                    b.ToTable("DeathInfo");
                });

            modelBuilder.Entity("UnityServerProject.Model.PlayerChapterInfo", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<long>("ChapterDuration")
                        .HasColumnType("bigint");

                    b.Property<string>("ChapterName")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayresultId")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("PlayresultId");

                    b.ToTable("PlayerChapterInfo");
                });

            modelBuilder.Entity("UnityServerProject.Model.Playresult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeadCount")
                        .HasColumnType("int");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsNormal")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("userplaydata");
                });

            modelBuilder.Entity("UnityServerProject.Model.StageDeathInfo", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("DeathCount")
                        .HasColumnType("int");

                    b.Property<int>("PlayresultId")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .HasColumnType("longtext");

                    b.HasKey("StageId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("PlayresultId");

                    b.ToTable("StageDeathInfo");
                });

            modelBuilder.Entity("UnityServerProject.Model.DeathInfo", b =>
                {
                    b.HasOne("UnityServerProject.Model.StageDeathInfo", "StageDeathInfo")
                        .WithMany("DeathInfos")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StageDeathInfo");
                });

            modelBuilder.Entity("UnityServerProject.Model.PlayerChapterInfo", b =>
                {
                    b.HasOne("UnityServerProject.Model.Playresult", "Playresult")
                        .WithMany("PlayerChapterInfos")
                        .HasForeignKey("PlayresultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playresult");
                });

            modelBuilder.Entity("UnityServerProject.Model.StageDeathInfo", b =>
                {
                    b.HasOne("UnityServerProject.Model.PlayerChapterInfo", "PlayerChapter")
                        .WithMany("StageDeathInfos")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnityServerProject.Model.Playresult", "Playresult")
                        .WithMany()
                        .HasForeignKey("PlayresultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerChapter");

                    b.Navigation("Playresult");
                });

            modelBuilder.Entity("UnityServerProject.Model.PlayerChapterInfo", b =>
                {
                    b.Navigation("StageDeathInfos");
                });

            modelBuilder.Entity("UnityServerProject.Model.Playresult", b =>
                {
                    b.Navigation("PlayerChapterInfos");
                });

            modelBuilder.Entity("UnityServerProject.Model.StageDeathInfo", b =>
                {
                    b.Navigation("DeathInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
